blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ íŒ€ì—ê²Œ ë¬¸ì˜í•˜ê¸°
    url: https://github.com/KB-its-your-life-Final-Project
    about: í…œí”Œë¦¿ ì™¸ ë¬¸ì˜ ì‚¬í•­ì€ Discussionsì—ì„œ í•´ì£¼ì„¸ìš”!
